espn_team_names = {
    "wsh": "Washington Commanders",
    "ten": "Tennessee Titans",
    "tb": "Tampa Bay Buccaneers",
    "sea": "Seattle Seahawks",
    "sf": "San Francisco 49ers",
    "lac": "Los Angeles Chargers",
    "lar": "Los Angeles Rams",
    "pit": "Pittsburgh Steelers",
    "phi": "Philadelphia Eagles",
    "lv": "Las Vegas Raiders",
    "nyj": "New York Jets",
    "nyg": "New York Giants",
    "no": "New Orleans Saints",
    "ne": "New England Patriots",
    "min": "Minnesota Vikings",
    "mia": "Miami Dolphins",
    "kc": "Kansas City Chiefs",
    "jax": "Jacksonville Jaguars",
    "ind": "Indianapolis Colts",
    "hou": "Houston Texans",
    "gb": "Green Bay Packers",
    "det": "Detroit Lions",
    "den": "Denver Broncos",
    "dal": "Dallas Cowboys",
    "cle": "Cleveland Browns",
    "cin": "Cincinnati Bengals",
    "chi": "Chicago Bears",
    "car": "Carolina Panthers",
    "buf": "Buffalo Bills",
    "bal": "Baltimore Ravens",
    "atl": "Atlanta Falcons",
    "ari": "Arizona Cardinals",
}
