# Generated by Django 2.0.5 on 2018-09-18 21:36

from django.conf import settings
from django.db import migrations


def addUserToPick(apps, schema_editor):
    ExistingRecords = apps.get_model('footballseason', 'Pick')
    ForeignKeyRecords = apps.get_model('auth', 'User')
    for pick in ExistingRecords.objects.all():
        users = ForeignKeyRecords.objects.filter(first_name=pick.user_name)

        assert len(users) == 1, "Found too many or too few users!"
        user = users[0]

        pick.user = user
        pick.save()


def addUserToRecord(apps, schema_editor):
    ExistingRecords = apps.get_model('footballseason', 'Record')
    ForeignKeyRecords = apps.get_model('auth', 'User')
    for record in ExistingRecords.objects.all():
        users = ForeignKeyRecords.objects.filter(first_name=record.user_name)

        assert len(users) == 1, "Found too many or too few users!"
        user = users[0]

        record.user = user
        record.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('footballseason', '0006_user_as_fk'),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.RunPython(addUserToPick),
        migrations.RunPython(addUserToRecord),
    ]
