# Generated by Django 2.0.5 on 2018-09-19 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footballseason', '0007_convert_username_to_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pick',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='user_name',
        ),
    ]
