# Generated by Django 2.0.5 on 2018-09-19 14:12

from django.db import migrations


def fix2015GameSeason(apps, schema_editor):
    gameRecords = apps.get_model('footballseason', 'Game')
    for game in gameRecords.objects.filter(season=0):
        game.season=2015
        game.save()


class Migration(migrations.Migration):

    dependencies = [
        ('footballseason', '0008_auto_20180919_0848'),
    ]

    operations = [
        migrations.RunPython(fix2015GameSeason),
    ]
