# Generated by Django 2.2.5 on 2021-11-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballseason', '0009_auto_20180919_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo_name',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
